CrossWordPuzzleGenerator/Controllers/PuzzleGeneratorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CrossWordPuzzleGenerator.Models;
using static CrossWordPuzzleGenerator.Models.ModelClasses;

namespace CrossWordPuzzleMaker.Controllers
{
    public class PuzzleGeneratorController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            ViewData["Sample"] = "اساس،الفبای،پارسی،عربی،نخستین،برجسته،الفبای،فارسی،دارای،چهار،حرف،شاهنشاهی،واجهای،متناظر،لغاتی،عربی،استاندارد،وجود،فرهنگ،جنوب غربی،حروف،رسمی";
            ViewBag.Puzzle = "";
            ViewBag.IsGenerated = false;
            return View();
        }

        [HttpPost]
        // GET: PuzzleGenerator
        public ActionResult Index(FormCollection form)
        { 
            var Allwords = Request.Form["words"];
            Allwords = Allwords.Replace(",", "،");
            Allwords = Allwords.Replace("،،", "،");
            Allwords = Allwords.Replace(" ", "");
            Allwords = Allwords.Replace(".", "");
            int dimention = 0;
            ViewData["Sample"] = Allwords;
            char[,] ch;
            string[] words = Allwords.Split('،');
            Random rnd = new Random();
            words = words.OrderByDescending(c => c.Length).ToArray();
            dimention = words.First().Length;
            bool result = false;
            WordInView[,] wiv = new WordInView[dimention,dimention];
            while (true)
            {
                ch = new char[dimention, dimention];
                Utilities.EmptyPuzzle(ch);
                result = Utilities.GeneratePuzzle(words, ch);
                if (result)
                {
                    char[,] answers = new char[dimention, dimention];
                    for (int i = 0; i < ch.GetLength(0); i++)
                    {
                        for (int j = 0; j < ch.GetLength(1); j++)
                        {
                            if (ch[i, j] == '-' || ch[i, j] == '\0')
                            {
                                answers[i, j] = '\0';
                            }
                            else
                            {
                                answers[i, j] = ch[i, j];
                            }
                        }
                    }
                    ViewBag.Answer = answers;
                    Utilities.FillWithRandomLetters(ch);
                    break;
                }
                else
                {
                    Utilities.PrintPuzzle(ch);
                    //words = words.OrderBy(x => rnd.Next()).ToArray();
                    Utilities.EmptyPuzzle(ch);
                    dimention++;
                }
            }
            ViewBag.IsGenerated = true;
            ViewBag.Puzzle = ch;
            return View(wiv);//RedirectToAction("Puzzle");
        }
    }
}

CrossWordPuzzleGenerator/Views/PuzzleGenerator/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
@using (Html.BeginForm("index", "PuzzleGenerator", FormMethod.Post))
{

    <div class="form-horizontal" style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif">

        <div class="form-group">
            <label class="control-label col-md-2" for="EnterWords">Enter Words seprated with ',' :</label>
            <div class="col-md-10">
                <textarea name="Words" class="form-control" id="Words" rows="3">@ViewData["Sample"]</textarea>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-10">
                <input type="submit" value="Generate" class="btn btn-default" />
            </div>
        </div>
        @if (ViewBag.IsGenerated)
        {
            <table class="table table-bordered" cellpadding="0" cellspacing="18" style="text-align: center">
                <tbody>
                    @for (int i = 0; i < Math.Sqrt(ViewBag.puzzle.Length); i++)
                    {
                        <tr>
                            @for (int j = 0; j < Math.Sqrt(ViewBag.puzzle.Length); j++)
                        {
                                <td>
                                    @ViewBag.puzzle[i, j]
                                </td>
                            }
                        </tr>
                    }
                </tbody>
            </table>

            <table class="table table-bordered" cellpadding="0" cellspacing="18" style="text-align: center">
                <tbody>
                    @for (int i = 0; i < Math.Sqrt(ViewBag.Answer.Length); i++)
                    {
                        <tr>
                            @for (int j = 0; j < Math.Sqrt(ViewBag.Answer.Length); j++)
                        {
                                <td>
                                    @ViewBag.Answer[i, j]
                                </td>
                            }
                        </tr>
                    }
                </tbody>
            </table>
        <p>Words are placed in up, down, left and right directions</p>
        <p><a href="https://gitlab.com/Moravej/PuzzleGenerator">View source Code on Gitlab</a></p>
        }
    </div>
}